//! Mock resources for the layer-2 harness — see mod.rs.
use super::Mock;
use crate::aws::service::ServiceType;
use crate::aws::services as svc;
use std::collections::HashMap;

pub(super) fn mocks() -> Vec<Mock> {
    vec![
        (
            ServiceType::EC2,
            "Ec2Instance",
            Box::new(svc::ec2::Ec2Instance::from_sdk(
                &aws_sdk_ec2::types::Instance::builder()
                    .instance_id("i-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::EC2,
            "Ami",
            Box::new(svc::ec2::Ami::from_sdk(
                &aws_sdk_ec2::types::Image::builder()
                    .image_id("ami-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::EC2,
            "EbsSnapshot",
            Box::new(svc::ec2::EbsSnapshot::from_sdk(
                &aws_sdk_ec2::types::Snapshot::builder()
                    .snapshot_id("snap-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::EC2,
            "EbsVolume",
            Box::new(svc::ec2::EbsVolume::from_sdk(
                &aws_sdk_ec2::types::Volume::builder()
                    .volume_id("vol-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::EC2,
            "LaunchTemplate",
            Box::new(svc::ec2::LaunchTemplate::from_sdk(
                &aws_sdk_ec2::types::LaunchTemplate::builder()
                    .launch_template_id("lt-0123456789abcdef0")
                    .launch_template_name("mock-lt")
                    .build(),
            )),
        ),
        (
            ServiceType::EC2,
            "SecurityGroup",
            Box::new(svc::ec2::SecurityGroup::from_sdk(
                &aws_sdk_ec2::types::SecurityGroup::builder()
                    .group_id("sg-0123456789abcdef0")
                    .group_name("mock-sg")
                    .vpc_id("vpc-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::EC2,
            "NetworkInterface",
            Box::new(svc::ec2::NetworkInterface::from_sdk(
                &aws_sdk_ec2::types::NetworkInterface::builder()
                    .network_interface_id("eni-0123456789abcdef0")
                    .vpc_id("vpc-0123456789abcdef0")
                    .subnet_id("subnet-0123456789abcdef0")
                    .private_ip_address("10.0.0.10")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "DhcpOptionsSet",
            Box::new(svc::vpc::DhcpOptionsSet::from_sdk(
                &aws_sdk_ec2::types::DhcpOptions::builder()
                    .dhcp_options_id("dopt-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "NatGateway",
            Box::new(svc::vpc::NatGateway::from_sdk(
                &aws_sdk_ec2::types::NatGateway::builder()
                    .nat_gateway_id("nat-0123456789abcdef0")
                    .vpc_id("vpc-0123456789abcdef0")
                    .subnet_id("subnet-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "NetworkAcl",
            Box::new(svc::vpc::NetworkAcl::from_sdk(
                &aws_sdk_ec2::types::NetworkAcl::builder()
                    .network_acl_id("acl-0123456789abcdef0")
                    .vpc_id("vpc-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "PrefixList",
            Box::new(svc::vpc::PrefixList::from_sdk(
                &aws_sdk_ec2::types::ManagedPrefixList::builder()
                    .prefix_list_id("pl-0123456789abcdef0")
                    .prefix_list_name("mock-pl")
                    .owner_id("123456789012")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "RouteTable",
            Box::new(svc::vpc::RouteTable::from_sdk(
                &aws_sdk_ec2::types::RouteTable::builder()
                    .route_table_id("rtb-0123456789abcdef0")
                    .vpc_id("vpc-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "Subnet",
            Box::new(svc::vpc::Subnet::from_sdk(
                &aws_sdk_ec2::types::Subnet::builder()
                    .subnet_id("subnet-0123456789abcdef0")
                    .vpc_id("vpc-0123456789abcdef0")
                    .cidr_block("10.0.0.0/24")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "Vpc",
            Box::new(svc::vpc::Vpc::from_sdk(
                &aws_sdk_ec2::types::Vpc::builder()
                    .vpc_id("vpc-0123456789abcdef0")
                    .cidr_block("10.0.0.0/16")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "VpcEndpoint",
            Box::new(svc::vpc::VpcEndpoint::from_sdk(
                &aws_sdk_ec2::types::VpcEndpoint::builder()
                    .vpc_endpoint_id("vpce-0123456789abcdef0")
                    .vpc_id("vpc-0123456789abcdef0")
                    .service_name("com.amazonaws.us-east-1.s3")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "VpcPeering",
            Box::new(svc::vpc::VpcPeering::from_sdk(
                &aws_sdk_ec2::types::VpcPeeringConnection::builder()
                    .vpc_peering_connection_id("pcx-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "VpcSecurityGroup",
            Box::new(svc::vpc::VpcSecurityGroup::from_sdk(
                &aws_sdk_ec2::types::SecurityGroup::builder()
                    .group_id("sg-0123456789abcdef1")
                    .group_name("mock-vpc-sg")
                    .vpc_id("vpc-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::VPC,
            "VpnConnection",
            Box::new(svc::vpc::VpnConnection::from_sdk(
                &aws_sdk_ec2::types::VpnConnection::builder()
                    .vpn_connection_id("vpn-0123456789abcdef0")
                    .customer_gateway_id("cgw-0123456789abcdef0")
                    .build(),
                &HashMap::new(),
            )),
        ),
        (
            ServiceType::Asg,
            "AsgGroup",
            Box::new(svc::asg::AsgGroup::from_sdk(
                &aws_sdk_autoscaling::types::AutoScalingGroup::builder()
                    .auto_scaling_group_name("mock-asg")
                    .auto_scaling_group_arn(
                        "arn:aws:autoscaling:us-east-1:123456789012:autoScalingGroup:00000000-0000-0000-0000-000000000000:autoScalingGroupName/mock-asg",
                    )
                    .min_size(0)
                    .max_size(1)
                    .desired_capacity(0)
                    .default_cooldown(300)
                    .health_check_type("EC2")
                    .build(),
            )),
        ),
        (
            ServiceType::Lambda,
            "LambdaFunction",
            Box::new(svc::lambda::LambdaFunction::from_sdk(
                &aws_sdk_lambda::types::FunctionConfiguration::builder()
                    .function_name("mock-fn")
                    .function_arn("arn:aws:lambda:us-east-1:123456789012:function:mock-fn")
                    .build(),
            )),
        ),
        (
            ServiceType::TransitGateway,
            "TgwAttachment",
            Box::new(svc::transit_gateway::TgwAttachment::from_sdk(
                &aws_sdk_ec2::types::TransitGatewayAttachment::builder()
                    .transit_gateway_attachment_id("tgw-attach-0123456789abcdef0")
                    .transit_gateway_id("tgw-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::TransitGateway,
            "TgwRouteTable",
            Box::new(svc::transit_gateway::TgwRouteTable::from_sdk(
                &aws_sdk_ec2::types::TransitGatewayRouteTable::builder()
                    .transit_gateway_route_table_id("tgw-rtb-0123456789abcdef0")
                    .transit_gateway_id("tgw-0123456789abcdef0")
                    .build(),
            )),
        ),
        (
            ServiceType::TransitGateway,
            "TransitGateway",
            Box::new(svc::transit_gateway::TransitGateway::from_sdk(
                &aws_sdk_ec2::types::TransitGateway::builder()
                    .transit_gateway_id("tgw-0123456789abcdef0")
                    .transit_gateway_arn("arn:aws:ec2:us-east-1:123456789012:transit-gateway/tgw-0123456789abcdef0")
                    .build(),
            )),
        ),
    ]
}
